- hosts: all
  become: true
  vars:
    softwarenames:
      - git 
      - nginx
  tasks:
    - name: install-java
      shell: |
        cd /opt
        wget https://download.java.net/openjdk/jdk17.0.0.1/ri/openjdk-17.0.0.1+2_linux-x64_bin.tar.gz
        tar -xvzf openjdk-17.0.0.1+2_linux-x64_bin.tar.gz
        rm openjdk-17.0.0.1+2_linux-x64_bin.tar.gz
        mv jdk-17.0.0.1  java-17
        ln -s /opt/java-17/bin/java /usr/bin/java
        echo 'export JAVA_HOME=/opt/java-17' | sudo tee -a /etc/profile
        echo 'export PATH=$PATH:$JAVA_HOME/bin' | sudo tee -a /etc/profile
        source /etc/profile

        java -version
      tags:
        - install java-17
    - name: install sonarqube
      shell: |
        cd /opt
        wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-25.6.0.109173.zip
        unzip sonarqube-25.6.0.109173.zip
        rm -r sonarqube-25.6.0.109173.zip
        mv sonarqube-25.6.0.109173 /opt/sonarqube
        useradd -r -M sonar
        chown -R sonar:sonar /opt/sonarqube
      tags: 
       - installation of sonarqube completed
    - name: enable enable sonar services 
      copy: 
       dest: /etc/systemd/system/sonarqube.service
       content: |
        [Unit]
        Description=SonarQube 25.6.0
        After=network.target

        [Service]
        Type=forking
        User=sonar
        Group=sonar
        ExecStart=/opt/sonarqube/bin/linux-x86-64/sonar.sh start
        ExecStop=/opt/sonarqube/bin/linux-x86-64/sonar.sh stop
        LimitNOFILE=65536
        Restart=always

        [Install]
        WantedBy=multi-user.target
      notify: 
        - Reload systemd

    
    - name: Enable and start sonar qube services
      service:
       name: sonarqube
       state: started
       enabled: true


    - name: Installsoftwares
      package: 
        name: "{{item}}"
        state: present
      loop: "{{softwarenames}}" 
      tags:
      - Installsoftwares
    - name: enable-nginx-services
      service:
        name: nginx
        state: started
        enabled: true
      tags: enable Nginx service  
  
  handlers:
    - name: Reload systemd 
      systemd: 
       daemon_reload: true     

      


