- hosts: all
  become: true
  vars:
    softwarenames:
      - git 
      - nginx
  tasks:
    - name: install-java
      shell: |
        cd /opt
        wget https://download.java.net/openjdk/jdk17.0.0.1/ri/openjdk-17.0.0.1+2_linux-x64_bin.tar.gz
        tar -xvzf openjdk-17.0.0.1+2_linux-x64_bin.tar.gz
        rm openjdk-17.0.0.1+2_linux-x64_bin.tar.gz
        mv jdk-17.0.0.1  java-17
        ln -s /opt/java-17/bin/java /usr/bin/java
        echo 'export JAVA_HOME=/opt/java-17' | sudo tee -a /etc/profile
        echo 'export PATH=$PATH:$JAVA_HOME/bin' | sudo tee -a /etc/profile
        source /etc/profile

        java -version
      tags:
        - install java-17
    - name: Installsoftwares
      package: 
        name: "{{item}}"
        state: present
      loop: "{{softwarenames}}" 
      tags:
      - Installsoftwares
    - name: enable-nginx-services
      service:
        name: nginx
        state: started
        enable: true
      tag: enable Nginx service    

      


